### ISSUE TITLE
Laravel 5.5 support

### ISSUE THREAD

**Issue by antonkomarev** [reshadman/file-secretary#1]
Is there any plans to add support of Laravel 5.5 in near future?

Only 5.1 supported right now.
```
"laravel/framework": ">=5.1.0 <5.2.0",
```

**Comment by reshadman** [comment]
@a-komarev 
No plan for near future, you can make a PR on another branch, the 2.* version will support
Laravel >= 5.5.0
We are testing this package in our production env which is 5.1
so our main focus is on:

-  making the interface much simpler
- add specific roadmap features
-  improve performance and design

**Comment by antonkomarev** [comment]
@reshadman thank you for detailed answer.

**Comment by reshadman** [comment]
If you are interested in the functionalities for newer versions of Laravel use [spatie/laravel-medialibrary](https://github.com/spatie/laravel-medialibrary) and for image resizing use [thumbor](https://github.com/thumbor/thumbor)
