### ISSUE TITLE
Video tutorial

### ISSUE THREAD

**Issue by nwaughachukwuma** [reshadman/file-secretary#3]
Hi @reshadman this a great work you have done. But the documentation is somewhat intimidating and daunting. Could you create a web-page (e.g. lesk.it) that is properly segmented to help discuss the features, functions and usage of the package? Also it will be nice if you made a video tutorial showing what this package offers. Thanks

**Comment by reshadman** [comment]
@nwaughachukwuma I will provide some better docs in github wiki pages, soon.
